# Site settings
title: Link Players and Games # your BLOG's name
header-img: "img/green.jpg" # colour of header image ?
tagline: "cn"
description: "Yzn's Blog"
baseurl: ""
url: "https://linkplayersandgames.com"

# About/Contact
owner:
  name: "Ye Zenan"
  email: "znye1996@gmail.com"
  bio: "xxxxxxxxxxxxxxxxxxxx"

# Data
gavatar: img/favicon.png
favicon: img/favicon.png

douban_username:
twitter_username:
github_username:
facebook_username:
weibo_username:
zhihu_username:

# Build settings
# use Github Flavoured Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

#Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      author: "Ye Zenan"
      header-msg: "img/green.jpg"

# Comments
comments :
  provider : disqus # apply disqus comments module
  duoshuo: 
  short_name:
  disqus:
  short_name:

# Analytics and webmaster tools stuff goes here
google_analytics:  # 填写你  google_analytics id
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
